// import './globals.scss'
import SearchPokemon from '@/components/SearchPokemon/SearchPokemon'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PokeNext',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <SearchPokemon/>
          {children}
        </main>
      </body>
    </html>
  )
}
